#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Testing and building project before committing'

# Check Prettier standards
echo 'Checking Prettier. 💅'
npm run check-format ||
(
    echo '❌ Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
echo 'Checking ESlint rules. 📋'
npm run check-lint ||
(
        echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
echo 'Validating types. 🤖'
npm run check-types ||
(
    echo '❌ Typescript tsconfig fail. Make the changes required above, add changes and try to commit again.'
    false;
)

# Try to build the project
echo 'Trying to build. 👷🔨'

npm run build ||
(
    echo '❌ Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅ Sucess! Your commit is being made'
